export * from './my-teams/my-teams';
export * from './game/game';
export * from './teams/teams';
export * from './team-detail/team-detail';
export * from './tournaments/tournaments';
export * from './team-home/team-home';
export * from './standings/standings';
export * from './map/map.page';
export * from './geolocation/geolocation';
export * from './camera/camera';
export * from './weather/weather'
